apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-bridge.backend.fullname" . }}
  labels:
    {{- include "ai-bridge.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
